### ISSUE TITLE
Placeholder image flickers

### ISSUE THREAD

**Issue by natalieeeflores** [renefloor/flutter_cached_network_image#165]
Hi! I have encountered an issue where the placeholder image flickers. I have seen this occur when the `fadeInDuration` is set.

Here is a gif of the issue:
![Kapture 2019-04-18 at 10 02 56](https://user-images.githubusercontent.com/19349394/56378980-7e7aba00-61c3-11e9-8a40-d55ad5d97196.gif)

Here is a reproduction case:
```dart
import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Cached Image'),
        ),
        body: Container(
          padding: EdgeInsets.only(top: 15),
          alignment: AlignmentDirectional.topCenter,
          child: CachedNetworkImage(
            placeholder: (_, __) => Container(
                  height: 200,
                  width: 350,
                  color: Colors.pink,
                ),
            fadeInDuration: Duration(milliseconds: 200),
            imageUrl:
                'https://assets3.thrillist.com/v1/image/2799859/size/tmg-article_default_mobile.jpg',
            fit: BoxFit.cover,
            height: 200,
            width: 350,
          ),
        ),
      ),
    );
  }
}
```

I have noticed this happen consistently when changing the `fadeInDuration` and `fadeOutDuration` from the default values. When the `fadeInDuration` is less than the default value this issue will consistently occur. When changing both I have seen the image flicker even if the `fadeInDuration` (set at 300 milliseconds) is more than twice as large as the `fadeOutDuration` (set at 100 milliseconds).

I think this issue is also related: https://github.com/renefloor/flutter_cached_network_image/issues/141

```
[flutter] flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.4 18E226, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.33.1)
[✓] Connected device (1 available)

• No issues found!
exit code 0
```

**Comment by Arcrueid** [comment]
I think the problem is that first load the image from the cache and then again from the url.

**Comment by Kavantix** [comment]
@natalieeeflores could you try using my adjusted version of the fade animation.
You can use this by replacing the dependency in your pubspec with:
```yaml
 cached_network_image:
    git: git@github.com:Kavantix/flutter_cached_network_image.git
```

**Comment by lifetin** [comment]
我也遇到相同的问题了.

**Comment by renefloor** [comment]
Should be fixed in 1.1.0, if not please reopen this issue

**Comment by zhusupq** [comment]
I think here same error:

 cached_network_image: ^3.3.0

https://github.com/Baseflow/flutter_cached_network_image/assets/50781959/422bc8ee-68b7-44e1-b2af-1a226cf6cc82

 ```
Scaffold(
      body: Center(
        child: SizedBox(
          height: 200,
          width: 200,
          child: CachedNetworkImage(
            imageUrl:
                "https://images.unsplash.com/photo-1699795836286-9987d11ca969?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTcwMDQyODMzMg&ixlib=rb-4.0.3&q=80&w=1080",
            imageBuilder: (context, imageProvider) => Container(
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: imageProvider,
                  fit: BoxFit.cover,
                ),
              ),
            ),
            placeholder: (a, b) => Container(
              color: Colors.red,
            ),
            // placeholder: (a, b) => const BlurHash(
            //   hash: 'QEFgB;V@oes:s.fPRjt6S2}?sAofxFoLafR+s.WqI;j[s.W;n%S2WVoLjZ',
            // ),
            fadeInDuration: Duration.zero,
            fadeOutDuration: Duration.zero,
            errorWidget: (context, url, error) => const Icon(Icons.error),
          ),
        ),
      ),
    )
```

**Comment by zhusupq** [comment]
@renefloor

**Comment by SlavaFreshcut** [comment]
Why this ticket is closed? It is still reproduced with the latest version

**Comment by filipljusic** [comment]
Still happening @renefloor

**Comment by FayozbekJumabekov** [comment]
is there any solution for this? 
White flash showed before image loaded
